// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Provider } from "@/components/ui/provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html suppressHydrationWarning>
//       {/* <link rel="preconnect" href="https://fonts.googleapis.com"></link>
//       <link rel="preconnect" href="https://fonts.gstatic.com"></link>
//       <link
//         href="https://fonts.googleapis.com/css2?family=Inter:wght@700&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
//         rel="stylesheet"
//       ></link> */}
//       <body>
//         <div className=" min-h-[100vh] w-[100vw] overflow-hidden">
//           {/* <Provider> */}
//           <>{children}</>
//           {/* </Provider> */}
//         </div>
//       </body>
//     </html>
//   );
// }]
"use client";
import { SessionProvider } from "next-auth/react";
import type { ReactNode } from "react";
import "./globals.css";

export default function RootLayout({ children }: { children: ReactNode }) {
  <>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@700&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />
  </>;
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
